=== assalmeftahi/xviz/modules/schema/declarative-ui/panel.schema.json
{
  "id": "https://xviz.org/schema/declarative-ui/panel.json",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Declarative UI Panel Info",
  "allOf": [{ "$ref": "#/definitions/with_children" }],
  "properties": {
    "type": {
      "enum": ["panel"]
    },
    "name": {},
    "layout": {},
    "interactions": {},
    "children": {}
  },
  "additionalProperties": false,
  "definitions": {
    "with_children": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "layout": {
          "type": "string",
          "enum": ["vertical", "horizontal"]
        },
        "interactions": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "reorderable",
              "dragout"
            ]
          },
          "additionalItems": false
        },
        "children": {
          "type": "array",
          "items": {
            "anyOf": [
              {"$ref": "https://xviz.org/schema/declarative-ui/components/metric.json"},
              {"$ref": "https://xviz.org/schema/declarative-ui/components/plot.json"},
              {"$ref": "https://xviz.org/schema/declarative-ui/components/table.json"},
              {"$ref": "https://xviz.org/schema/declarative-ui/components/treetable.json"},
              {"$ref": "https://xviz.org/schema/declarative-ui/components/video.json"},
              {"$ref": "#/definitions/container"}
            ]
          },
          "additionalItems": false
        }
      },
      "required": [
        "name",
        "children"
      ]
    },
    "container": {
      "title": "container",
      "description": "Group of components",
      "allOf": [{ "$ref": "#/definitions/with_children" }],
      "properties": {
        "type": {
          "enum": ["container"]
        },
        "name": {},
        "layout": {},
        "interactions": {},
        "children": {}
      },
      "required": [
        "type"
      ],
      "additionalProperties": false
    }
  }
}

=== assalmeftahi/xviz/modules/schema/examples/declarative-ui/panel/complete.json
{
  "type": "panel",
  "layout": "vertical",
  "name": "Example Panel",
  "interactions": ["reorderable"],
  "children": [

    {
      "type": "container",
      "layout": "horizontal",
      "name": "Example Container #1",
      "interactions": ["dragout"],
      "children": [
        {
          "type": "table",
          "title": "A nested table showing something",
          "description": "These are the details of this table",
          "stream": "/some/table_stream",
          "displayObjectId": false
        },
        {
          "type": "plot",
          "title": "A nested plot!",
          "description": "The change in some streams as a function of the other one",
          "independentVariable": "/some/stream",
          "dependentVariables": [
            "/some/other_stream",
            "/some/second_other_stream"
          ]
        },
        {
          "title": "Additional Info Type",
          "description": "Which type of additional information you want sent",
          "type": "select",
          "stream": "/system/additional_info/types",
          "onchange": {
            "target": "/system/info/type"
          }
        }
      ]
    },

    {
      "type": "table",
      "title": "A table showing something",
      "description": "These are the details of this table",
      "displayObjectId": true,
      "stream": "/prediction/some_table"
    },

    {
      "type": "metric",
      "title": "Some metric",
      "description": "The actual vs commanded value for some variable",
      "streams": [
        "/some_value/actual",
        "/some_value/commanded"
      ]
    },

    {
      "type": "plot",
      "title": "Some Other Streams vs Some Stream",
      "description": "The change in some streams as a function of the other one",
      "independentVariable": "/some/stream",
      "dependentVariables": [
        "/some/other_stream",
        "/some/second_other_stream"
      ]
    },

    {
      "type": "video",
      "cameras": [
        "front-center-roof-camera",
        "rear-starboard-roof-camera",
        "rear-port-roof-camera"
      ]
    },

    {
      "type": "treetable",
      "title": "A TreeTable!",
      "description": "These are the details of the TreeTable",
      "displayObjectId": false,
      "stream": "/some/stream/of/treetable/primmatives"
    }

  ]
}
